### ISSUE TITLE
Adding Keypad plugin to ember project 

### ISSUE THREAD

**Issue by phatle** [nolimits4web/Framework7-Keypad#2]
I already added Framework7 to my Ember cli project. But I can not make Keypad works. My initialize file: 

```
export function initialize(container, application) {
  var f7 = new window.Framework7();

  application.register('f7:main', f7, { instantiate: false });
  application.inject('route', 'f7', 'f7:main');
  application.inject('controller', 'f7', 'f7:main');
  application.inject('component', 'f7', 'f7:main');
  application.inject('view', 'f7', 'f7:main');
}

export default {
  name: 'framework7-service',
  initialize: initialize
};
```

I included Keypad js and css file in Brocfile.js:

```
app.import({
  development: 'bower_components/framework7-keypad/dist/framework7.keypad.css',
  production: 'bower_components/framework7-keypad/dist/framework7.keypad.min.css'
});

app.import({
  development: 'bower_components/framework7-keypad/dist/framework7.keypad.js',
  production: 'bower_components/framework7-keypad/dist/framework7.keypad.min.js'
});
```
When I use ```<input type="numpad">``` it's not working, nothing happen. 
I figure out that when running the code: ```var f7 = new window.Framework7();```, the plugin is not found(or hooked)

**Comment by nolimits4web** [comment]
I am not too good in Ember, but as i guess, you may have this issue because you include plugin file after you initialize app with `var f7 = new window.Framework7()`. So you can grab them manually by calling `f7.initPlugins()`

**Comment by phatle** [comment]
I did call ```f7.initPlugins()``` but nothing happened. I figure out that it's because of  ```strict mode```.
I got this error message: ```Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at Function.remoteFunction (<anonymous>:3:14)
    at Object.InjectedScript.callFunctionOn (<anonymous>:750:66)
    at window.Framework7.app.pluginHook
...........```

At line:
```
// Plugin Hooks
        app.pluginHook = function (hook) {
            for (var i = 0; i < _plugins.length; i++) {
                if (_plugins[i].hooks && hook in _plugins[i].hooks) {
//THIS LINE
                    _plugins[i].hooks[hook](arguments[1], arguments[2], arguments[3], arguments[4], arguments[5]);
                }
            }
        };
```

**Comment by nolimits4web** [comment]
Everything fine with this line and it is valid for strict mode. According to your error message, error is  somewhere in `Function.remoteFunction (<anonymous>:3:14)`. That is probably something on Ember side

**Comment by phatle** [comment]
Oh. I see. I create a static html file(not ember project) and still got this error. But the keypad is displayed well. Thank you.

**Comment by nolimits4web** [comment]
Yes, but these functions `Function.remoteFunction` and `Object.InjectedScript.callFunctionOn ` where error happens, are not F7's function and not native JS function, so i guess it is something wrong with Ember

**Comment by phatle** [comment]
I found the problem. It missed some Framework7 classes like ```.page....```. Thank you for your help.
